#!/bin/bash

FILES=("/epics/synApps/synApps_6_3/support/motor-R7-3-1/lib/linux-arm/libzynqMotor.a" "/epics/synApps/synApps_6_3/support/motor-R7-3-1/lib/linux-arm/libzynqMotor.so" "/epics/iocs/zynqIoc/zynqApp/src/Makefile")

while true; do
    inotifywait -e modify "${FILES[@]}"

    make

    build_date=$(date)
    echo "Last built $build_date"

done
