/*
 * Auto-generated by firmware/src/scripts/gen_zynq_motor_regs.py
 * Source of truth: firmware/src/pkg/generic_pkg.sv
 *                  firmware/src/pkg/drv8xxx_pkg.sv
 *                  firmware/src/hdl/drv8xxx_register.sv
 *                  firmware/src/hdl/global_register.sv
 *
 * Do not edit manually.
 */

#ifndef ZYNQ_MOTOR_REGS_GEN_HPP
#define ZYNQ_MOTOR_REGS_GEN_HPP

#include <cstddef>
#include <cstdint>
#include <sys/types.h>

static constexpr off_t MOTOR_REG_OFFSET = 0x100;
static constexpr off_t MOTOR_REG_STRIDE = 0x30;
static constexpr std::size_t REG_SIZE = 0x1000;

static constexpr off_t REG_DEVICE = 0x00;
static constexpr off_t REG_VERSION = 0x04;
static constexpr off_t REG_GIT_HASH = 0x08;
static constexpr off_t REG_RESERVED = 0x0C;

static constexpr off_t REG_CFG = 0x00;
static constexpr off_t REG_STEP_RATE = 0x04;
static constexpr off_t REG_CONTROL = 0x08;
static constexpr off_t REG_STEP_SP = 0x0C;
static constexpr off_t REG_STEP_RB = 0x10;
static constexpr off_t REG_POS_SP_LO = 0x14;
static constexpr off_t REG_POS_SP_HI = 0x18;
static constexpr off_t REG_POS_RB_LO = 0x1C;
static constexpr off_t REG_POS_RB_HI = 0x20;
static constexpr off_t REG_STATUS = 0x24;

static constexpr uint8_t CFG_LIMIT_EN_BIT = 0;
static constexpr uint8_t CFG_LIMIT_POL_BIT = 1;
static constexpr uint8_t CFG_USTEP_MODE_BIT = 8;
static constexpr uint8_t CFG_USTEP_MODE_WID = 8;

static constexpr uint8_t CTRL_EN_BIT = 0;
static constexpr uint8_t CTRL_RESET_BIT = 1;
static constexpr uint8_t CTRL_SLEEP_BIT = 2;
static constexpr uint8_t CTRL_DIR_BIT = 3;
static constexpr uint8_t CTRL_POS_SET_BIT = 4;
static constexpr uint8_t CTRL_MSTART_BIT = 5;
static constexpr uint8_t CTRL_MSTOP_BIT = 6;

static constexpr uint8_t STAT_FAULT_BIT = 0;
static constexpr uint8_t STAT_MOVING_BIT = 1;
static constexpr uint8_t STAT_PLIMIT_BIT = 2;
static constexpr uint8_t STAT_NLIMIT_BIT = 3;

#endif // ZYNQ_MOTOR_REGS_GEN_HPP
